id: A82C58BB4
title: Toh_225-Taking_Refuge_in_the_Three_Jewels-v2
type: translation
pechas:
- I06327A93
- I969C660C
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-063-006
  eft-text-version: 1.0.2 2020
  title: Toh_225-Taking_Refuge_in_the_Three_Jewels-v2
alignment_to_base:
  I06327A93/AB85: F633
  I969C660C/EE11: F633
